Local variables i variables with dynamic content generated by the core class, for usage in view files.<br>
And makes it easier to read and maintain the code and structure in view files<br>
<br>
<strong>$template</strong><br>
Will contain all methods and properties of the <strong>template.class.php</strong> use it to make your code more readable. also referred to as 'the object'
<br><br>
<strong>$stylesheets</strong><br>
Contains DOM structure for each of the stylesheets added through controllers <strong>screen.css</strong> is default and should not be removed
<br><br>
<strong>$javascript</strong><br>
Contains DOM structure for javascript files added through controllers <strong>main.css</strong> is the default and will only be included if it exists
<br><br>
<strong>$messages</strong><br>
Contains all the system messages generated through the controller files.<br>
Same effect can also be achieved with <strong>$template->messages()</strong>
<br><br>
<strong>$title</strong><br>
The title of the requested page, set in function <strong>hook_pages()</strong>
<br><br>
You can also create your own local variables in controller files with <pre>$this->data["variable-name"] = "value";</pre>